import fs from 'node:fs/promises';
import { profile as p, publications, news } from '../site-data.js';
const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
await fs.mkdir('assets',{recursive:true});
// Original vector placeholder artwork: layered ridgelines and a seeded forest.
let seed=31;
const random=()=>{seed=(seed*16807)%2147483647;return (seed-1)/2147483646};
let trees='';
for(let layer=0;layer<4;layer++)for(let i=0;i<65;i++){
  const x=i*28+random()*25,base=620+layer*115+Math.sin(x/260)*65,h=80+random()*140+layer*25,w=h*.35;
  trees+=`<path d="M${x} ${base-h} l${w} ${h*.72} h${-w*.4} l${w*.65} ${h*.28} h${-w*2.5} l${w*.65} ${-h*.28} h${-w*.4}Z" fill="${['#486751','#34583f','#244731','#143724'][layer]}"/>`;
}
await fs.writeFile('assets/forest.svg',`<svg xmlns="http://www.w3.org/2000/svg" width="1800" height="1100" viewBox="0 0 1800 1100"><defs><linearGradient id="sky" x2="0" y2="1"><stop stop-color="#819781"/><stop offset="1" stop-color="#d5d5ad"/></linearGradient><radialGradient id="sun"><stop stop-color="#e9e7b9" stop-opacity=".6"/><stop offset="1" stop-color="#e9e7b9" stop-opacity="0"/></radialGradient></defs><path fill="url(#sky)" d="M0 0h1800v1100H0z"/><circle cx="1270" cy="220" r="350" fill="url(#sun)"/><path d="M0 500Q200 180 420 370T870 340T1320 280T1800 350V1100H0Z" fill="#7b917c"/><path d="M0 630Q250 320 540 480T1050 430T1500 460T1800 390V1100H0Z" fill="#637f68"/><path d="M0 770Q300 510 600 590T1100 510T1800 600V1100H0Z" fill="#506d53"/>${trees}<path d="M0 1040Q400 900 800 1020T1800 980V1100H0Z" fill="#102d20"/></svg>`);
const art=(kind,color)=>`<svg xmlns="http://www.w3.org/2000/svg" width="700" height="480" viewBox="0 0 700 480"><rect width="700" height="480" fill="${color}"/><g fill="none" stroke="#f1f2df" stroke-opacity=".5">${Array.from({length:14},(_,i)=>kind==='rings'?`<ellipse cx="350" cy="230" rx="${30+i*23}" ry="${20+i*15}" transform="rotate(-23 350 230)"/>`:kind==='grid'?`<path d="M${i*55} 0v480M0 ${i*40}h700"/>`:`<path d="M-50 ${i*30+20}Q180 ${i*22-40} 360 ${i*30+40}T750 ${i*24+90}"/>`).join('')}</g><text x="30" y="445" fill="#f1f2df" font-family="monospace" font-size="11" letter-spacing="3">${kind.toUpperCase()} / IMAGE PLACEHOLDER</text></svg>`;
for(const [k,c] of [['rings','#71876b'],['grid','#56746c'],['waves','#9b9c7e']])await fs.writeFile(`assets/${k}.svg`,art(k,c));
const nav=[
  {page:'home',href:'home.html',label:'HOME'},
  {page:'research',href:'research.html',label:'RESEARCH'},
  {page:'media',href:'media.html',label:'MEDIA'},
  {href:'CV_Zejun-Wu.pdf',label:'CV',external:true},
  {page:'blog',href:'blog.html',label:'EXPLORER'}
];
const external=(href,text,cls='text-link')=>`<a class="${cls}" href="${esc(href)}" target="_blank" rel="noopener noreferrer">${text} <span aria-hidden="true">↗</span></a>`;
const head=title=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${title} · Zejun Wu</title><meta name="description" content="Zejun Wu — Remote sensing, plant ecology and LiDAR. Research and publications at the University of Virginia."><meta name="theme-color" content="#243c33"><link rel="icon" type="image/svg+xml" href="assets/favicon.svg"><link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="layout.css"><script>document.documentElement.classList.add('js')</script><script src="app.js" defer></script></head>`;
const header=page=>`<a class="skip" href="#main">Skip to content</a><header class="header"><div class="wrap header-inner"><div class="brand-group"><a class="wordmark" href="home.html" aria-label="Zejun Wu — Home"><span class="brand-mark" aria-hidden="true">ZW</span><span class="brand-name">Zejun Wu</span></a><div class="header-socials"><a class="scholar-icon" href="${p.scholar}" target="_blank" rel="noopener noreferrer" aria-label="Zejun Wu on Google Scholar"><span aria-hidden="true">G</span></a><a class="linkedin-icon" href="${p.linkedin}" target="_blank" rel="noopener noreferrer" aria-label="Zejun Wu on LinkedIn"><span aria-hidden="true">in</span></a></div></div><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu ☰</button><nav class="nav" id="navigation" aria-label="Main navigation">${nav.map(n=>`<a href="${n.href}" ${n.page===page?'aria-current="page"':''}${n.external?' target="_blank" rel="noopener noreferrer"':''}>${n.label}</a>`).join('')}</nav></div></header>`;
const footer=()=>`<footer class="footer"><div class="wrap"><span>© ${new Date().getFullYear()} Zejun Wu · A personal academic website</span><a href="index.html">Back to the opening scene ↗</a></div></footer>`;
const page=(name,content)=>head(name.toUpperCase())+`<body>${header(name)}<main class="wrap" id="main">${content}</main>${footer()}</body></html>`;
const heading=(n,title,desc)=>`<div class="page-heading"><p class="eyebrow">${n} / Zejun Wu</p><h1>${title}</h1><p>${desc}</p></div>`;
const pub=r=>`<article class="paper" data-type="${r.type}"><div class="year">${r.year}</div><div><span class="badge">${r.type}</span><h3><a href="https://scholar.google.com/citations?view_op=view_citation&amp;user=0g9DJbAAAAAJ&amp;citation_for_view=0g9DJbAAAAAJ:${r.id}" target="_blank" rel="noopener noreferrer">${esc(r.title)}</a></h3><p>${esc(r.authors)}</p><p><em>${esc(r.venue)}</em></p></div><span class="paper-arrow" aria-hidden="true">↗</span></article>`;
await fs.writeFile('assets/favicon.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="10" fill="#243c33"/><text x="32" y="45" text-anchor="middle" fill="#f5f4ed" font-size="42" font-family="Georgia">Z</text></svg>');
await fs.writeFile('index.html',head('Welcome')+`<body class="landing"><main class="landing-shell"><div class="landscape" aria-hidden="true"><img src="assets/forest.svg" alt=""></div><header class="landing-top"><a class="wordmark" href="home.html">ZW.</a><a href="home.html">SKIP INTRO ↗</a></header><div class="landing-content"><div class="eyebrow">Remote sensing · Plant ecology · LiDAR</div><h1>Zejun <em>Wu.</em></h1><p>Exploring the natural world.<br>From individual leaves to forest canopies.</p><a class="enter" href="home.html">ENTER MY WEBSITE <span aria-hidden="true">→</span></a></div><span class="art-label">FOREST STUDY — ILLUSTRATED PLACEHOLDER</span><footer class="landing-bottom"><span>UNIVERSITY OF VIRGINIA<br>PERSONAL ACADEMIC WEBSITE</span><button data-motion aria-pressed="false">Pause animation</button></footer></main></body></html>`);
const newsCards = () => news.map(n => `<article class="news-card">${n.video ? `<video controls playsinline preload="metadata" aria-label="PERS Lab video from the Puerto Rico field campaign"><source src="${esc(n.video)}" type="video/mp4">Your browser cannot play this video. <a href="${esc(n.video)}">Open fieldwork video</a>.</video>` : `<img src="${esc(n.image)}" alt="${esc(n.alt)}" loading="lazy" width="700" height="440">`}<div class="news-body"><div class="news-meta"><span>${esc(n.category)}</span><time datetime="${n.date}">${n.date}</time></div><h3>${esc(n.title)}</h3><p>${esc(n.text)}</p>${external(p.labUrl+'#news','Source: PERS Lab')}</div></article>`).join('');
const newsRows = () => news.map(n => `<article class="news-row"><time datetime="${n.date}">${n.date}</time><div><span class="news-category">${esc(n.category)}</span><h3>${esc(n.title)}</h3><p>${esc(n.text)}</p>${external(p.labUrl+'#news','Source: PERS Lab')}</div></article>`).join('');
const newsSection = `<section class="section news-section home-news" id="news" aria-labelledby="news-heading"><div class="news-heading"><h2 id="news-heading">News</h2></div><div class="news-scroll" tabindex="0" aria-label="Recent news; scroll for more">${newsRows()}</div></section>`;
await fs.writeFile('home.html',page('home',`<section class="intro about"><div class="intro-copy"><p class="eyebrow">Welcome to my little corner of the world</p><h1>About me<span>.</span></h1><div class="about-text"><p>Hi, I’m a PhD candidate in the <a href="https://geoxiyang.github.io/PERS-Website/" target="_blank" rel="noopener noreferrer">Plant Ecology and Remote Sensing Lab</a>, advised by Prof. Xi Yang, in the Department of Environmental Sciences at the University of Virginia (UVA). Previously, I earned my MSc with Distinction in Ecological Applications from <a href="https://www.imperial.ac.uk/silwood-park/" target="_blank" rel="noopener noreferrer">Imperial College London</a> and received a First-Class Honours BSc in Environmental Science from the University of Liverpool and Xi’an Jiaotong-Liverpool University. Before coming to UVA, I spent one year as a research assistant in <a href="https://wu-jin.weebly.com/" target="_blank" rel="noopener noreferrer">Prof. Jin Wu’s group</a> at the University of Hong Kong.</p><p>My independent research began in plant physiology, where I conducted laboratory experiments to investigate plant responses to environmental stress, particularly heavy metal and microplastic pollution, supervised by <a href="https://scholar.xjtlu.edu.cn/en/persons/LinxiYuan/" target="_blank" rel="noopener noreferrer">Prof. Linxi Yuan</a> during my undergraduate studies. Then, I expanded my research to modelling tree ecophysiology and seasonal dynamics at larger scales, including spring leaf phenology and optimality-based photosynthetic models.</p><p>Currently, my research interests broadly span anything related to plant and forest ecology, terrestrial ecosystems, remote sensing, and AI for environmental observation. I combine LiDAR, remote sensing, field measurements, and statistical/machine-learning approaches to translate complex environmental data into interpretable ecological information and uncover the mechanisms underlying observed patterns. My recent work focuses on using terrestrial and airborne LiDAR (TLS/ALS) to understand forest structure and function across spatial and temporal scales.</p><p>I’d love to connect with and learn from people working on similar problems. Feel free to reach out by <a href="mailto:jjmyn@virginia.edu">email</a>.</p></div></div><figure class="portrait"><img src="avatar.jpg" alt="Portrait of Zejun Wu in graduation attire" width="3649" height="4562" fetchpriority="high"><figcaption><span>Zejun Wu</span><span>A moment to remember</span></figcaption></figure></section>${newsSection}<section class="section contact"><div><span class="number">02 / SAY HELLO</span><h2>Let’s stay connected.</h2><p>For academic updates and professional connections.</p></div><div><div class="links">${external(p.scholar,'Google Scholar')}${external(p.linkedin,'LinkedIn')}<a class="text-link" href="mailto:jjmyn@virginia.edu">Email <span aria-hidden="true">↗</span></a></div></div></section>`));
await fs.writeFile('research.html',page('research',heading('01','Research & publications.','Remote sensing, plant ecology, and the structure of our living world.')+`<div class="filters" aria-label="Filter publications"><button data-filter="all" aria-pressed="true">All publications</button><button data-filter="Journal article" aria-pressed="false">Journal articles</button><button data-filter="Conference abstract" aria-pressed="false">Conference abstracts</button><span id="result-count" role="status">3 publications</span></div>${publications.map(pub).join('')}<p class="source">Publication metadata checked against ${external(p.scholar,'Google Scholar')} on ${p.verifiedOn}. Conference abstracts are listed separately from journal articles.</p><section class="section"><h2>Research in progress</h2><p>${p.research}</p><p>Recent fieldwork includes TLS surveys at NEON sites and a tropical forest campaign near El Yunque, Puerto Rico, with the MACROCOSM project.</p>${external(p.labUrl+'#people','Research profile at PERS Lab')}</section>`));
const configs={media:['02','Media & moments.','A space for talks, conversations, and stories from research.',['Talks & presentations','In the field','In the news'],['Talk title, event, and recording link will appear here.','Fieldwork photographs and a short story will appear here.','Press coverage and interviews will appear here.']],blog:['03','Notes along the way.','Research reflections, field notes, and things worth remembering.',['A note from the field','Behind the research','Beyond the lab'],['A future field journal entry will appear here.','A future research reflection will appear here.','A future personal essay will appear here.']]};
for(const [name,[n,title,desc,titles,descriptions]] of Object.entries(configs)){
  const cards=titles.map((t,i)=>`<article class="card"><img src="assets/${['rings','grid','waves'][i]}.svg" alt="Abstract ${['contour rings','coordinate grid','flowing lines'][i]} — placeholder illustration" loading="lazy"><span class="badge">Coming soon / Placeholder</span><h2>${t}</h2><p>${descriptions[i]}</p><details><summary>About this space</summary><p>This is a layout placeholder. ${name==='blog'?'No article has been published yet.':'No media item has been added yet.'}</p></details></article>`).join('');
  await fs.writeFile(`${name}.html`,page(name,heading(n,title,desc)+`<div class="cards">${cards}</div>`));
}
await fs.writeFile('media.html',page('media',heading('02','Fieldwork & lab news.','Recent field campaigns and announcements from the PERS Lab.')+`<div class="news-grid">${newsCards()}</div><p class="source">Photos and video: PERS Lab. The photograph accompanying the award announcement shows TLS fieldwork at Bartlett Experimental Forest, not an award ceremony.</p>`));
console.log('Built opening scene + 4 pages and 5 original SVG assets.');
